# Generated by Django 4.2.1 on 2023-05-29 20:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_record', models.CharField(max_length=50, null=True, unique=True)),
                ('Expediente', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Paciente', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_Paterno', models.CharField(max_length=100)),
                ('Apellido_Materno', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('Estado_Civil', models.CharField(blank=True, max_length=30, null=True)),
                ('Ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Nacionalidad', models.CharField(blank=True, max_length=30, null=True)),
                ('Domicilio', models.CharField(blank=True, max_length=400, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='pacientes_fotos')),
                ('id_Expediente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.record')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('-id',),
            },
        ),
    ]
